# Generated by Django 2.2.1 on 2019-05-03 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleLinkedNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='algorithm.Node')),
            ],
            bases=('algorithm.node',),
        ),
        migrations.CreateModel(
            name='DoubleLinkedNode',
            fields=[
                ('singlelinkednode_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='algorithm.SingleLinkedNode')),
            ],
            bases=('algorithm.singlelinkednode',),
        ),
    ]
