# Generated by Django 2.2.2 on 2019-06-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0002_doublelinkednode_singlelinkednode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='algorithm.Node')),
            ],
            bases=('algorithm.node',),
        ),
    ]
