# Generated by Django 2.2.2 on 2019-07-01 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('algorithm', '0003_treenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('node_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='algorithm.Node')),
            ],
            bases=('algorithm.node',),
        ),
    ]
